apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        role: web
        tier: backend
    spec:
      containers:
      - name: web
        image: kysnm/docker-airflow:1.10.2
        imagePullPolicy: Always
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 8080
        env:
        - name: LOAD_EX
          value: 'y'
        - name: AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX
          value: 'True'
        - name: EXECUTOR
          value: Celery
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: '3306'
        - name: MYSQL_USER
          value: airflow
        - name: MYSQL_PASSWORD
          value: airflow
        - name: MYSQL_DB
          value: airflow
        - name: REDIS_HOST
          value: redis-deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        role: scheduler
        tier: backend
    spec:
      containers:
      - name: scheduler
        image: kysnm/docker-airflow:1.10.2
        imagePullPolicy: Always
        args:
        - scheduler
        env:
        - name: LOAD_EX
          value: 'y'
        - name: AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX
          value: 'True'
        - name: EXECUTOR
          value: Celery
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: '3306'
        - name: MYSQL_USER
          value: airflow
        - name: MYSQL_PASSWORD
          value: airflow
        - name: MYSQL_DB
          value: airflow
        - name: REDIS_HOST
          value: redis-deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-worker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: airflow
        role: worker
        tier: backend
    spec:
      containers:
      - name: worker
        image: kysnm/docker-airflow:1.10.2
        imagePullPolicy: Always
        args:
        - worker
        env:
        - name: LOAD_EX
          value: 'y'
        - name: AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX
          value: 'True'
        - name: EXECUTOR
          value: Celery
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: '3306'
        - name: MYSQL_USER
          value: airflow
        - name: MYSQL_PASSWORD
          value: airflow
        - name: MYSQL_DB
          value: airflow
        - name: REDIS_HOST
          value: redis-deployment
